### ISSUE TITLE
Do not work on android device

### ISSUE THREAD

**Issue by Viald** [LedgerHQ/app-security-key#10]
Hi.
When trying to auth for Google (or others site) on Chrome for Android, it just gets stuck in an authentication loop forever asking to allow Play Services access to the security key over and over again, like if the app was crashing on every attempt.

That's the same issue with the previous U2F authentication app on LNX and LNS+.
Check this video to see what's happening. https://dai.ly/k6RjcJI85fIJ6YyLnY6

**Comment by xchapron-ledger** [comment]
Hello, there shouldn't be any need for the Ledger Live on your phone to use the FIDO applications. Can you try it without the Ledger live app? Maybe by uninstalling it temporally?

**Comment by xchapron-ledger** [comment]
Hello,
I'm not 100% sure, but I found [this](https://passkeys.dev/docs/reference/android/) and I'm wondering if that means that FIDO2 (the techno behind passkeys) doesn't work on Android as of now?
![image](https://github.com/LedgerHQ/app-security-key/assets/107417453/7deec882-9491-4a04-89f3-c439f4a98677)

**Comment by xchapron-ledger** [comment]
Hello @Viald , I just wanted to let you know that with the app version 1.4.0 which will be deployed once https://github.com/LedgerHQ/app-security-key/pull/27 is merged, the app will be compatible with Chrome on Android.
Note that as of now this require:
- an android device with up-to-date Google Play service version (something like at least september 2023)
- a website using the setting "discoverable credential = discouraged", else, as of now, you can't select an external security key and are force to use Google Passkey. You can test it on website like webauthn.io

**Comment by Viald** [comment]
Thank you @xchapron-ledger for pointing me this update. I will test it as soon as it will be available.

**Comment by xchapron-ledger** [comment]
@Viald the version has just been deployed.

I'm clausing this issue as as far as I know this now works on up to date Android device (when Android allows a roaming authenticator - aka when Discoverable credential settings as been set to discouraged by the RP as of now).

**Comment by Viald** [comment]
Hello. It works like a charm. Thank you so much :)
