### ISSUE TITLE
U2F not working with Security Keys for Apple ID

### ISSUE THREAD

**Issue by juliolustosa** [LedgerHQ/app-security-key#12]
U2F not working with Security Keys for Apple ID

Doc: https://support.apple.com/en-us/HT213154

App Name: Fido U2F
App version: 1.3.1

Ledger Nano X
Firmware: 2.2.1

**Comment by xchapron-ledger** [comment]
@juliolustosa I'm not sure you got my point here: https://github.com/LedgerHQ/app-u2f/issues/15#issuecomment-1561516489
You need to install another app.
