### ISSUE TITLE
Possibility to disable PIN code for new enrollment ?

### ISSUE THREAD

**Issue by Viald** [LedgerHQ/app-security-key#19]
Hi.
Like the previous app Fido U2F, could you add the option to disable the PIN code request when trying to enroll new accounts ? With a long PIN code I often face a action timeout from the server.

Thanks

**Comment by xchapron-ledger** [comment]
@Viald Hello, you can disable it by removing the call to `os_ux_blocking(&params)` in `src/ctap2_processing.c ``performBuiltInUv()` function. Though I'm not sure I will create a dedicated Makefile flag for this.

I take the opportunity to ask you on what platform / service have you successfully used the app?
Thanks.

**Comment by Viald** [comment]
Hello @xchapron-ledger. It will be easier if it's an option in the app like the previous app FIDO U2F. 
I use it with github, Google, bitwarden, Dropbox.

**Comment by xchapron-ledger** [comment]
@Viald Note that new version 1.3.0 (not release yet) dropped the PIN request but still request for user approval.

**Comment by Viald** [comment]
@xchapron-ledger I can't wait to test it 👍

**Comment by xchapron-ledger** [comment]
@Viald It is available on the Ledger live with default settings.

**Comment by Viald** [comment]
@xchapron-ledger it seems there is an issue with the version displayed by the app.
Ledger live shows 1.3.0 installed, but the app displays version 1.1.1

**Comment by xchapron-ledger** [comment]
> @xchapron-ledger it seems there is an issue with the version displayed by the app. Ledger live shows 1.3.0 installed, but the app displays version 1.1.1
> 
> Update: I need to uninstall and reinstall the app to solve the issue.

That's an issue within Ledger Live which doesn't detect correctly the version of the app due to an app specificity.
To update the app, you need to uninstall it and then reinstall it.
