### ISSUE TITLE
NOT AN ISSUE: This also works with on Nano S Plus and an iPhone with an OTG cable.

### ISSUE THREAD

**Issue by Noonlord** [LedgerHQ/app-security-key#21]
As Nano S Plus doesn't support iOS I was slightly confused about if this would work on an iPhone with OTG cable. I guessed that as FIDO2 is a standard and iOS supports it, it should. And good news, it works! I think it would be nice to add this to blog post.

**Comment by xchapron-ledger** [comment]
@Noonlord I'm glad it worked for you.
Indeed iOS support FIDO2 standard and therefore made an exception for USB device using FIDO2 HID endpoint.
The blog post normally says that it works under the "Compatibility" section.

Note that there are changes coming around September hopefully which might improve the user experience (reducing most  limitations from the blog post).

Anyway, I'm glad it worked for you. Can you tell us a bit more what you tried? Which browser? Which services?
Thanks.

**Comment by Noonlord** [comment]
"On iOS 14 and iPadOS 15.5 and later, it is supported on Safari, Chrome and Firefox" It says this on blog post but I was confused as Ledger Nano S Plus itself doesn't support iOS, but figured that it is a standard and should work after all! 

I tried on Safari with Google (passekey) and GitHub (2fa) both worked really well! Thanks for great work. I wanted a FIDO2 device for a long time and this is really cool. It cost me less than a Yubi Security Key and I can safely hold my stablecoins too. Really looking forward to new update.

**Comment by xchapron-ledger** [comment]
Ok, thanks for the info, will try to make it clearer that it works on iOS over USB fro Nanox and NanoSP.
I'm closing these as resolved. Feel free to open a new issue if needed.
