### ISSUE TITLE
No credential found for this domain

### ISSUE THREAD

**Issue by valebedu** [LedgerHQ/app-security-key#23]
## Data

- OS version: macOS Ventura 13.5.2
- Chip: Apple M1 Pro
- Device used: Ledger Nano X
- Ledger version: 2.2.2
- Security Key version: 1.1.1
- Browser used: Google Chrome
- Google chrome version: 117.0.5938.92 (Official Build) (arm64)

## Issue

I followed the article on ledger blog: https://blog.ledger.com/security-key/ and follow these steps

1. Download Ledger Live and select the Security Key application in the “My Ledger” section to install it on your device
2. Set the appropriate settings on the desired service (AWS, Dropbox, Facebook, Google, GitHub, Microsoft, Twitter, …)
3. Use your security key to Log In !

And didn't get it about how to associate my ledger to passkey on external services. I tried on google to add a passkey by following these steps:

1. Launch Security Key application on ledger
2. Click on "+ Create a passkey"
3. Click on "Use another device"
5. Click on "Use a different device"
6. Click on "USB security key"
7. Ledger display "No credential found for this domain" on page one and "Domain Google" on page 2 with the only possible interaction to "<- Close"

I probably miss something but the blog is not really exhaustive so that's difficult to understand what's missing

And also I didn't understand if the key used for passkey is derived like in the Fido U2F app and then if I reboot my device if my passkey association will still works.

**Comment by valebedu** [comment]
Hi @xchapron-ledger,

It looks like you're the author of the blog post, please can you help, it's not really an issue but more a misunderstanding about how it works, can you please explain a bit more ?

Thanks,

**Comment by xchapron-ledger** [comment]
Hi @valebedu 
Several change were made on the app since the 1.1.1 and the blog post.

I suppose you have another security key registered on your google Account ? I think that your UX issue will be fixed by the soon to come release 1.3.0.

**Comment by valebedu** [comment]
That's right I have 2 more hardware keys used as 2FA. I'll wait for the 1.3.0 then

**Comment by valebedu** [comment]
Do you have an idea of the release data? And also I don't understand, i see that a tag for a 1.2.0 of the application exists in the repo but in Ledger Live the last version I see is 1.1.1, do you know why?

**Comment by valebedu** [comment]
Fixed in 1.3.0
