### ISSUE TITLE
Nano S: Screensaver and the FIDO2 App

### ISSUE THREAD

**Issue by My1** [LedgerHQ/app-security-key#33]
Apparently getting a request in does not wake the ledger up and ask for PIN or confirmation, but rather, it just runs the line of text until it goes off screen and seemingly just stays black until you push a button.

**Comment by xchapron-ledger** [comment]
Correct, I forgot to add a few `UX_WAKE_UP();` code to wake up the device properly when it's locked.
I'm fixing this.
Can you confirm that what your are talking about?

When the device is pin locked (screen saver running, and pin asked upon interaction) and a request is received, it should exit the screensaver and ask for the PIN.

**Comment by My1** [comment]
Yes, but in addition it also doesn't wake up if the screensaver is active but the pin has not triggered yet (as you can set the timings differently)

**Comment by xchapron-ledger** [comment]
@My1 Should be fixed in the 1.5.1 version of the app now available in Ledger Live.
