### ISSUE TITLE
Clarify Limitations

### ISSUE THREAD

**Issue by green-pass** [LedgerHQ/app-security-key#6]
Limitations section from https://blog.ledger.com/security-key/ is not quite clear to someone who is not security expert.

I have some questions. for example by backing up your recovery seed phrase of your wallet. you can recreate all your crypto accounts on any other ledger device (or even other such crypto hardware wallets). there are also other open source apps and libs that you can to feed your seed and get private keys.

i.e. you have many options to recover private keys of your accounts.

With this app what I would expect is to have similar UX.  tho looking at limitations it's not quite like that because I don't quite understand those technical details that much I don't quite see what the UX should be.

If I have this app and I use it to sign in google. and I loose the key am i screwed? are there some libs you can use to restore those keys to get access to google? can I go buy another ledger device use same seed install this app  and get same keys to sign in google?

It would be great if all this details were discussed in long form video / podcast for example.

also this is great! and I love having more none crypto usecases for ledger.

**Comment by Anprotaku** [comment]
Is there something that can be done to backup the Resident keys? and upload them to a "restored/new" device with the same seed.

**Comment by xchapron-ledger** [comment]
> Is there something that can be done to backup the Resident keys? and upload them to a "restored/new" device with the same seed.

@Anprotaku Hello :)

A backup and restore mechanism could be implemented. It would be really manual and for advance users, but that would be a first step.

**Comment by xchapron-ledger** [comment]
For backup and restore option, let's keep this issue: https://github.com/LedgerHQ/app-security-key/issues/7

For limitations, they are mentioned here: https://www.ledger.com/blog/strengthen-the-security-of-your-accounts-with-webauthn and kept up-to-date as much as possible.

**Comment by makeitstrict** [comment]
<img width="1290" height="1257" alt="Image" src="https://github.com/user-attachments/assets/141a6595-5833-414f-8567-0cbfc02a861d" />
Hello, @xchapron-ledger !
Is it not true anymore or how I can do that? I went through entire device settings and Ledger live but failed to find anything similar

**Comment by xchapron-ledger** [comment]
Hello @makeitstrict ,
I no longer work at Ledger and therefore I don't maintain anymore this application anymore.
I believe @iartemov-ledger is the one currently maintaining this app now.

**Comment by iartemov-ledger** [comment]
Hello @makeitstrict ,

The manual activation of the resident key feature was removed in v1.6.4. 
The rational behind was that it was too error-prone even for experienced users and and too frustrating in the case of key loss at an update. 

The feature is not abandoned. The idea is to support reliable and secure app data backup/restore through Ledger Live and then re-enable the feature in the Security Key app.

**Comment by makeitstrict** [comment]
Hello @iartemov-ledger and thank you for explanation.
However I don't see any use cases working with this app rn.
According to my tests there're no use cases working correctly at all:
- Binance Passkeys(macOS 15.6; USB-C; Safari) — "attestation signature verification fail(10233521-6d96256d)"
- Base Smart Wallet Sign-Up(macOS 15.6; USB-C; Safari) — No reaction
- iCloud Two-Factor auth(macOS 15.6; USB-C) — Completely hangs my Stax and no reaction on system side
- Many other cases but not a single one with success

Maybe you should consider hide this app under experimental flag to not confuse people about feature-completeness of that app? Don't get me wrong, I know that it's not your main focus nor the main thing of ledger wallet, but as a customer I expect to get from internal marketplace somewhat working apps whereas this one looks more like an early experiment.

**Comment by iartemov-ledger** [comment]
Hello @makeitstrict ,

In app-security-key v1.7.1 we found a regression with attestation keys that we fixed with v1.7.2 deployed on Nano X 2.5.0, Nano S Plus 1.4.0, Stax 1.8.0 and Flex 1.4.0. 
Please update to this version. We tested the registration and authentication with Binance using browser and mobile app and that was working again. 
Yes, the Security Key app might not the main focus, but we do our best do maintain and evolve it.
