### ISSUE TITLE
Should it work with Bluetooth connexion ?

### ISSUE THREAD

**Issue by Viald** [LedgerHQ/app-security-key#9]
Hi Xavier.
Thank you for this great new app. It works well using USB connexion. What about Bluetooth connexion ? Should it work with the LNX ?
Thanks

**Comment by xchapron-ledger** [comment]
@Viald Hello :)
No BLE support has not been developed for this app as of now.

**Comment by Viald** [comment]
Thanks. Is it in your roadmap ?

**Comment by xchapron-ledger** [comment]
> Thanks. Is it in your roadmap ?

As far as I aware, this is not in the roadmap.

**Comment by Viald** [comment]
In such case, no real interest to have Nano X.
